-- 10-1
CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP3;



-- DROP TABLE DEPT_TEMP;
-- DROP TABLE DEPT_TEMP2;
-- DROP TABLE EMP_TEMP;
-- CREATE TABLE DEPT_TEMP10;
-- --     AS SELECT * FROM EMP;

-- SELECT * FROM DEPT_TEMP10;

-- 10-3
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
                VALUES( 50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

-- 10-4
INSERT INTO DEPT_TEMP
        VALUES(60    , 'NETWORK', 'BUSAN');

SELECT * FROM DEPT_TEMP;


-- 10-5
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
                VALUES(70   ,'WEB', NULL);
SELECT * FROM DEPT_TEMP;

-- 10-6
INSERT INTO DEPT_TEMP (DEPTNO, DNAME    , LOC)
                VALUES (80  ,'MOBILE', '');
SELECT * FROM DEPT_TEMP;

-- 10-7
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
                VALUES (90  , 'INCHEON');
SELECT * FROM DEPT_TEMP;



-- 10-8
CREATE TABLE EMP_TEMP
    AS SELECT * 
        FROM EMP
    WHERE 1 <> 1;
-- 10-8
SELECT * FROM EMP_TEMP; 

SELECT * FROM EMP;

-- 10-9
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR,
 HIREDATE, SAL, COMM, DEPTNO)
        VALUES ( 9999, '홍길동', 'PRESIDENT', NULL, 
        TO_DATE('2001-01-01', 'YYYY-MM-DD'), 5000, 1000, 10);
SELECT * FROM EMP_TEMP; 

-- 10-10
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR,
 HIREDATE, SAL, COMM, DEPTNO)
        VALUES ( 1111, '성춘향', 'MANAGER', 9999, TO_DATE('2001-01-05', 'YYYY-MM-DD'), 5000, 1000, 10);
SELECT * FROM EMP_TEMP; 


-- 10-11
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR,
 HIREDATE, SAL, COMM, DEPTNO)
    VALUES (2111, '이순신', 'MANAGER', 9999,
     TO_DATE('2001-01-05', 'YYYY-MM-DD'), 4000, NULL, 20);


-- DELETE FROM EMP_TEMP 
-- WHERE ENAME = '이순신' 
-- AND HIREDATE = TO_DATE('05/01/2001', 'DD/MM/YYYY');

-- 10-12
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR,
 HIREDATE, SAL, COMM, DEPTNO)
    VALUES (2111, '이순신', 'MANAGER', 9999,
     TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);
SELECT * FROM EMP_TEMP; 


--  10-13
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

SELECT * FROM EMP_TEMP;

--  10-14
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
  FROM EMP E, SALGRADE S
 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
   AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

--  10-15
CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

--  10-16
UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

--  10-17
ROLLBACK;

--  10-18
UPDATE DEPT_TEMP2
   SET DNAME = 'DATABASE',
         LOC = 'SEOUL'
 WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--  10-19
UPDATE DEPT_TEMP2
   SET (DNAME, LOC) = (SELECT DNAME, LOC
                         FROM DEPT
                        WHERE DEPTNO = 40)
 WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--  10-20
UPDATE DEPT_TEMP2
   SET DNAME = (SELECT DNAME
                  FROM DEPT
                 WHERE DEPTNO = 40),
       LOC = (SELECT LOC
                FROM DEPT
               WHERE DEPTNO = 40)
 WHERE DEPTNO = 40;

--  10-21
UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL'
 WHERE DEPTNO = (SELECT DEPTNO
                   FROM DEPT_TEMP2
                  WHERE DNAME='OPERATIONS');

SELECT * FROM DEPT_TEMP2;

--  10-22
CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

--  10-23
DELETE FROM EMP_TEMP2
 WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

--  10-24
DELETE FROM EMP_TEMP2
 WHERE EMPNO IN (SELECT E.EMPNO
                   FROM EMP_TEMP2 E, SALGRADE S
                  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 3
                    AND DEPTNO = 30);

SELECT * FROM EMP_TEMP2;

--  10-25
DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;

--5> 사원번호가 7566인 사원의 이름 및 부서번호를 출력하라.
SELECT e.*, d.*
FROM employees e
JOIN departments d ON e.department_id = d.department_id
WHERE e.salary > 2000;

