-- 13-1, 13-2
SELECT * FROM DICT;
SELECT * FROM DICTIONARY;

-- 사용자 권한 객체, 등 조회 기능이 
-- 포함 된 데이터 베이스 운영과 관련된 정보를 저장하고 있음.

-- 13-3
SELECT TABLE_NAME
    FROM USER_TABLES;


-- 13-4
SELECT OWNER, TABLE_NAME
    FROM  ALL_TABLES;

-- 13-5
SELECT * FROM DBA_TABLES;

-- 13-6
SELECT * FROM DBA_TABLES;

-- 13-7
SELECT *
    FROM DBA_USERS
WHERE USERNAME = 'SCOTT';

-- 13-8
SELECT *
    FROM USER_INDEXES;

-- 13-9
SELECT *
    FROM USER_IND_COLUMNS;

-- 13-10
CREATE INDEX IDX_SAL
    ON EMP(SAL);

-- 13-11
SELECT * FROM USER_IND_COLUMNS;

-- 13-12
DROP INDEX IDX_SAL;

-- 13-13
SELECT * FROM USER_IND_COLUMNS;

 -- 13-15
CREATE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
        FROM EMP
        WHERE DEPTNO = 20);

SELECT * 
    FROM VW_EMP20;

-- 13-17
SELECT VIEW_NAME, TEXT_LENGTH, TEXT
    FROM USER_VIEWS;

-- 13-18
SELECT *
    FROM VW_EMP20;

-- 13-19
DROP VIEW VW_EMP20;

-- 13-20
SELECT ROWNUM, E.*
    FROM EMP E;

-- 13-21
SELECT ROWNUM, E.*
    FROM EMP E
    ORDER BY SAL DESC;

-- 13-22
SELECT ROWNUM, E.*
    FROM (SELECT *
            FROM EMP E
            ORDER BY SAL DESC) E;

-- 13-23
WITH E AS (SELECT * FROM EMP E ORDER BY SAL DESC)
SELECT ROWNUM, E.*
    FROM E;

-- 13-24
SELECT ROWNUM, E.*
    FROM (SELECT *
            FROM EMP E
            ORDER BY SAL DESC) E
WHERE ROWNUM <= 3;


-- 13-25
WITH E AS (SELECT * FROM EMP E ORDER BY SAL DESC)
SELECT ROWNUM, E.*
    FROM E
WHERE ROWNUM <= 3;

-- 13-26
CREATE TABLE DEPT_SEQUENCE
    AS SELECT * 
            FROM DEPT
        WHERE 1 <> 1;

SELECT * FROM DEPT_SEQUENCE;
-- dsd