-- 두개 이상의 테이블을 가로로 연결한 것 join

SELECT *
    FROM DEPT;

SELECT *
    FROM EMP;

-- 두개의 테이블을 SELECT해서 두 테이블이 둘다 세로로 나옴
-- 모든 행 조합들이 모두 출력 되게 됨
-- 스미스가 모든 부서에 있는 것처럼 나오게 되버림
SELECT *
    FROM EMP, DEPT
ORDER BY EMPNO;

SELECT *
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMPNO;


-- 별칭 지정 하기
SELECT *
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

-- SELECT * 거의 사용하지 말기
-- 이유: 어떤 열을 선택했는지 알 수 없음

-- DEPT 테이블의 부서 이름, EMP 테이블의 사원 번호를 출력
SELECT E.EMPNO, D.DEPTNO
    FROM EMP E, DEPT D 
    WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

-- 가로로 늘어뜨려서 출력하는 JOIN


-- 등가 조인
-- 특정 열의 값과 일치하는 행만 출력함
SELECT EMPNO, ENAME, D.DEPTNO, DNAME, LOC
    FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;



SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.EMPNO, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL >= 3000;



-- 데카르트의 곱, 조인으로 묶을시 테이블 개수-1로 조건식을 해야됨

SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D;


SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
    AND SAL <= 2500
    AND E.EMPNO  <=9999;

SELECT * FROM EMP;
SELECT * FROM SALGRADE;


-- 비등가 조인
SELECT *
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- 자체 조인
-- 스스로를 복사해서 조인
-- 사원의 해당하는 직속 상관 까지도 출력하게 할 때
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
        FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO;

-- 외부 조인
-- NULL 값도 출력하기 위해서 사용함
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO(+)
    ORDER BY E1.EMPNO;


SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2
    WHERE E1.MGR(+) = E2.EMPNO
    ORDER BY E1.EMPNO;


-- NATURAL JOIN
-- 등가 조인
-- 기준 열만 테이블 이름을 붙이면 안됨.
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
 E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
    FROM EMP E NATURAL JOIN DEPT D
    ORDER BY DEPTNO, E.EMPNO;

-- JOIN ~USING
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
 E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE SAL >= 3000
    ORDER BY DEPTNO, E.EMPNO;

--JOIN ~ON
-- 조인 조건식을 ON 뒤에 명시함
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
 E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    WHERE SAL >= 3000
    ORDER BY DEPTNO, E.EMPNO;

-- OUTER JOIN
SELECT E1.EMPNO, E1.ENAME,E1.MGR,
 E2.EMPNO AS MGR_EMPNO,
 E2.ENAME AS MGR_ENAME
    FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO;

SELECT E1.EMPNO, E1.ENAME,E1.MGR,
 E2.EMPNO AS MGR_EMPNO,
 E2.ENAME AS MGR_ENAME
    FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY  E1.EMPNO, MGR_EMPNO;


SELECT E1.EMPNO, E1.ENAME,E1.MGR,
 E2.EMPNO AS MGR_EMPNO,
 E2.ENAME AS MGR_ENAME
    FROM EMP E1 FULL OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY  E1.EMPNO, MGR_EMPNO;